name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout out code
      uses: actions/checkout@v3
    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run lint checks
      run: ./gradlew lint
    
    - name: Run tests
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew build
