name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "release/**" ]
  pull_request:
    branches: [ "main", "release/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout out code
      uses: actions/checkout@v3

    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test --debug

    - name: Build with Gradle
      run: ./gradlew build
